;!knitout-2
;;Carriers: 1 2 3 4 5 6
x-stitch-number 5
x-roller-advance 500
;catch yarns
x-speed-number 300
in 6
knit + f40 6
knit + b41 6
miss + f45 6
knit - b43 6
knit - f42 6
knit - b39 6
knit + f40 6
knit + b45 6
knit - f42 6
knit - b41 6
miss - f39 6
knit + f40 6
knit + b41 6
miss + f45 6
in 5
knit + f40 5
knit + b41 5
knit + f44 5
knit + b45 5
knit - b39 5
knit + f40 5
knit + b43 5
knit + f44 5
miss + f45 5
knit - b43 5
miss - f39 5
knit + f40 5
knit + b41 5
knit + f44 5
knit + b45 5
in 3
knit + f40 3
knit + b41 3
miss + f45 3
knit - b45 3
knit - f44 3
knit - b39 3
knit + f40 3
knit + b45 3
knit - f44 3
knit - b43 3
miss - f39 3
miss - f17 3
in 2
knit + b39 2
knit + f40 2
knit + b45 2
knit - f42 2
knit - b39 2
knit + b41 2
knit + f44 2
miss + f45 2
knit - b43 2
miss - f39 2
knit + b39 2
knit + f40 2
knit + b45 2
;waste section
x-speed-number 400
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - f44 2
knit - b41 2
knit - f40 2
miss - f39 2
knit + b39 2
knit + f42 2
knit + b43 2
miss + f45 2
knit - b45 2
knit - b43 2
knit - b41 2
knit - b39 2
knit + f40 2
knit + f42 2
knit + f44 2
miss + f45 2
knit - b45 2
knit - b43 2
knit - b41 2
knit - b39 2
knit + f40 2
knit + f42 2
knit + f44 2
miss + f45 2
knit - b45 2
knit - b43 2
knit - b41 2
knit - b39 2
knit + f40 2
knit + f42 2
knit + f44 2
miss + f45 2
knit - b45 2
knit - b43 2
knit - b41 2
knit - b39 2
knit + f40 2
knit + f42 2
knit + f44 2
miss + f45 2
miss + f45 2
drop b39
drop b41
drop b43
drop b45
;draw thread
knit - f44 5
knit - f42 5
knit - f40 5
miss - f39 5
miss - f-2 5
;closed tube cast-on
x-speed-number 300
rack 0.25
knit - b45 2
knit - f44 2
knit - b43 2
knit - f42 2
knit - b41 2
knit - f40 2
knit - b39 2
rack 0
;begin main piece
;row: 0 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f40 2
knit + f42 2
knit + f44 2
miss + f45 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
;end jersey
x-stitch-number 5
;row: 1 (section 1/1)
;inc 1 on left (39 -> 38) by split
x-speed-number 100
rack -1
split - b39 f38 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
miss + f45 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
miss - b38 2
;end jersey
x-stitch-number 5
;row: 2 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
miss + f45 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
miss - b38 2
;end jersey
x-stitch-number 5
;row: 3 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
miss + f45 2
;end jersey
x-stitch-number 5
;inc 1 on right (45 -> 46) by split
x-speed-number 100
rack 1
split + b45 f46 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
miss - b38 2
;end jersey
x-stitch-number 5
;row: 4 (section 1/1)
;inc 1 on left (38 -> 37) by split
x-speed-number 100
rack 1
split - f38 b37 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
;end jersey
x-stitch-number 5
;row: 5 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
;end jersey
x-stitch-number 5
;row: 6 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
;end jersey
x-stitch-number 5
;inc 1 on right (46 -> 47) by split
x-speed-number 100
rack -1
split + f46 b47 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
;end jersey
x-stitch-number 5
;row: 7 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
miss + f47 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
;end jersey
x-stitch-number 5
;row: 8 (section 1/1)
;inc 1 on left (37 -> 36) by split
x-speed-number 100
rack -1
split - b37 f36 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
miss + f47 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
miss - b36 2
;end jersey
x-stitch-number 5
;row: 9 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
miss + f47 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
miss - b36 2
;end jersey
x-stitch-number 5
;row: 10 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
miss + f47 2
;end jersey
x-stitch-number 5
;inc 1 on right (47 -> 48) by split
x-speed-number 100
rack 1
split + b47 f48 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
miss - b36 2
;end jersey
x-stitch-number 5
;row: 11 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
miss - b36 2
;end jersey
x-stitch-number 5
;row: 12 (section 1/1)
;inc 1 on left (36 -> 35) by split
x-speed-number 100
rack 1
split - f36 b35 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
;end jersey
x-stitch-number 5
;row: 13 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
;end jersey
x-stitch-number 5
;row: 14 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
;end jersey
x-stitch-number 5
;inc 1 on right (48 -> 49) by split
x-speed-number 100
rack -1
split + f48 b49 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
;end jersey
x-stitch-number 5
;row: 15 (section 1/1)
;inc 1 on left (35 -> 34) by split
x-speed-number 100
rack -1
split - b35 f34 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
miss + f49 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
miss - b34 2
;end jersey
x-stitch-number 5
;row: 16 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
miss + f49 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
miss - b34 2
;end jersey
x-stitch-number 5
;row: 17 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
miss + f49 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
miss - b34 2
;end jersey
x-stitch-number 5
;row: 18 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
miss + f49 2
;end jersey
x-stitch-number 5
;inc 1 on right (49 -> 50) by split
x-speed-number 100
rack 1
split + b49 f50 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
miss - b34 2
;end jersey
x-stitch-number 5
;row: 19 (section 1/1)
;inc 1 on left (34 -> 33) by split
x-speed-number 100
rack 1
split - f34 b33 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
;end jersey
x-stitch-number 5
;row: 20 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
;end jersey
x-stitch-number 5
;row: 21 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
;end jersey
x-stitch-number 5
;inc 1 on right (50 -> 51) by split
x-speed-number 100
rack -1
split + f50 b51 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
;end jersey
x-stitch-number 5
;row: 22 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
miss + f51 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
;end jersey
x-stitch-number 5
;row: 23 (section 1/1)
;inc 1 on left (33 -> 32) by split
x-speed-number 100
rack -1
split - b33 f32 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
miss + f51 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
miss - b32 2
;end jersey
x-stitch-number 5
;row: 24 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
miss + f51 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
miss - b32 2
;end jersey
x-stitch-number 5
;row: 25 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
miss + f51 2
;end jersey
x-stitch-number 5
;inc 1 on right (51 -> 52) by split
x-speed-number 100
rack 1
split + b51 f52 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
miss - b32 2
;end jersey
x-stitch-number 5
;row: 26 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
miss - b32 2
;end jersey
x-stitch-number 5
;row: 27 (section 1/1)
;inc 1 on left (32 -> 31) by split
x-speed-number 100
rack 1
split - f32 b31 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
;end jersey
x-stitch-number 5
;row: 28 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
;end jersey
x-stitch-number 5
;row: 29 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
;end jersey
x-stitch-number 5
;inc 1 on right (52 -> 53) by split
x-speed-number 100
rack -1
split + f52 b53 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
;end jersey
x-stitch-number 5
;row: 30 (section 1/1)
;inc 1 on left (31 -> 30) by split
x-speed-number 100
rack -1
split - b31 f30 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
miss + f53 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
miss - b30 2
;end jersey
x-stitch-number 5
;row: 31 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
miss + f53 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
miss - b30 2
;end jersey
x-stitch-number 5
;row: 32 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
miss + f53 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
miss - b30 2
;end jersey
x-stitch-number 5
;row: 33 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
miss + f53 2
;end jersey
x-stitch-number 5
;inc 1 on right (53 -> 54) by split
x-speed-number 100
rack 1
split + b53 f54 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
miss - b30 2
;end jersey
x-stitch-number 5
;row: 34 (section 1/1)
;inc 1 on left (30 -> 29) by split
x-speed-number 100
rack 1
split - f30 b29 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
;end jersey
x-stitch-number 5
;inc 1 on right (54 -> 55) by split
x-speed-number 100
rack -1
split + f54 b55 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
;end jersey
x-stitch-number 5
;row: 35 (section 1/1)
;inc 1 on left (29 -> 28) by gradual split
x-speed-number 100
rack -1
split - b29 f28 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
miss + f55 2
;end jersey
x-stitch-number 5
;inc 1 on right (55 -> 56) by split
x-speed-number 100
rack 1
split + b55 f56 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
;end jersey
x-stitch-number 5
;row: 36 (section 1/1)
;inc 8 on left (27 -> 19) by zig-zag
rack 0.25
knit - f26 2
knit - b25 2
knit - f24 2
knit - b23 2
knit - f22 2
knit - b21 2
knit - f20 2
knit - b19 2
rack 0
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
;end jersey
x-stitch-number 5
;inc 9 on right (56 -> 65) by zig-zag
rack 0.25
knit + b57 2
knit + f58 2
knit + b59 2
knit + f60 2
knit + b61 2
knit + f62 2
knit + b63 2
knit + f64 2
knit + b65 2
rack 0
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
;end jersey
x-stitch-number 5
;row: 37 (section 1/1)
;inc 10 on left (19 -> 9) by zig-zag
rack 0.25
knit - f18 2
knit - b17 2
knit - f16 2
knit - b15 2
knit - f14 2
knit - b13 2
knit - f12 2
knit - b11 2
knit - f10 2
knit - b9 2
rack 0
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
miss + f65 2
;end jersey
x-stitch-number 5
;inc 10 on right (65 -> 75) by zig-zag
rack 0.25
knit + f66 2
knit + b67 2
knit + f68 2
knit + b69 2
knit + f70 2
knit + b71 2
knit + f72 2
knit + b73 2
knit + f74 2
knit + b75 2
rack 0
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
;end jersey
x-stitch-number 5
;row: 38 (section 1/1)
;inc 9 on left (9 -> 0) by zig-zag
rack 0.25
knit - f8 2
knit - b7 2
knit - f6 2
knit - b5 2
knit - f4 2
knit - b3 2
knit - f2 2
knit - b1 2
knit - f0 2
rack 0
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
miss + f75 2
;end jersey
x-stitch-number 5
;inc 8 on right (75 -> 83) by zig-zag
rack 0.25
knit + f76 2
knit + b77 2
knit + f78 2
knit + b79 2
knit + f80 2
knit + b81 2
knit + f82 2
knit + b83 2
rack 0
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b83 2
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
knit - b1 2
miss - b0 2
;end jersey
x-stitch-number 5
;row: 39 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
knit + f82 2
miss + f83 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b83 2
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
knit - b1 2
miss - b0 2
;end jersey
x-stitch-number 5
;row: 40 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
knit + f82 2
miss + f83 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b83 2
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
knit - b1 2
miss - b0 2
;end jersey
x-stitch-number 5
;row: 41 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
knit + f82 2
miss + f83 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b83 2
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
knit - b1 2
miss - b0 2
;end jersey
x-stitch-number 5
;row: 42 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
knit + f82 2
miss + f83 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b83 2
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
knit - b1 2
miss - b0 2
;end jersey
x-stitch-number 5
;row: 43 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
knit + f82 2
miss + f83 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b83 2
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
knit - b1 2
miss - b0 2
;end jersey
x-stitch-number 5
;row: 44 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
knit + f82 2
miss + f83 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b83 2
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
knit - b1 2
miss - b0 2
;end jersey
x-stitch-number 5
;row: 45 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
knit + f82 2
miss + f83 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b83 2
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
knit - b1 2
miss - b0 2
;end jersey
x-stitch-number 5
;row: 46 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
knit + f82 2
miss + f83 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b83 2
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
;twisted stitch
x-add-roller-advance -500
miss - b1 2
x-add-roller-advance -500
knit + b1 2
miss - b0 2
;end jersey
x-stitch-number 5
;row: 47 (section 1/1)
;dec 1 on left (0 -> 1)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f0 b1
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
;twisted stitch
x-add-roller-advance -500
miss + f82 2
x-add-roller-advance -500
knit - f82 2
;end jersey
x-stitch-number 5
miss + f83 2
;dec 1 on right (83 -> 82)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b83 f82
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
knit - b1 2
;end jersey
x-stitch-number 5
;row: 48 (section 1/1)
;dec 1 on left (1 -> 2)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b1 f2
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
;twisted stitch
x-add-roller-advance -500
miss + f28 2
x-add-roller-advance -500
knit - f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
miss + f81 2
;end jersey
x-stitch-number 5
knit + f82 2
;dec 1 on right (82 -> 81)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f82 b81
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b81 2
x-add-roller-advance -500
knit + b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
;twisted stitch
x-add-roller-advance -500
miss - b3 2
x-add-roller-advance -500
knit + b3 2
miss - b2 2
;end jersey
x-stitch-number 5
;row: 49 (section 1/1)
;dec 1 on left (2 -> 3)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f2 b3
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
knit + f80 2
miss + f81 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b81 2
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
knit - b3 2
;end jersey
x-stitch-number 5
;row: 50 (section 1/1)
;dec 1 on left (3 -> 4)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b3 f4
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
;twisted stitch
x-add-roller-advance -500
miss + f48 2
x-add-roller-advance -500
knit - f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
;twisted stitch
x-add-roller-advance -500
miss + f80 2
x-add-roller-advance -500
knit - f80 2
;end jersey
x-stitch-number 5
miss + f81 2
;dec 1 on right (81 -> 80)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b81 f80
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
miss - b4 2
;end jersey
x-stitch-number 5
;row: 51 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
knit + f78 2
miss + f79 2
;end jersey
x-stitch-number 5
knit + f80 2
;dec 1 on right (80 -> 79)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f80 b79
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b79 2
x-add-roller-advance -500
knit + b79 2
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
;twisted stitch
x-add-roller-advance -500
miss - b5 2
x-add-roller-advance -500
knit + b5 2
miss - b4 2
;end jersey
x-stitch-number 5
;row: 52 (section 1/1)
;dec 1 on left (4 -> 5)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f4 b5
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
;twisted stitch
x-add-roller-advance -500
miss + f78 2
x-add-roller-advance -500
knit - f78 2
;end jersey
x-stitch-number 5
miss + f79 2
;dec 1 on right (79 -> 78)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b79 f78
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
knit - b5 2
;end jersey
x-stitch-number 5
;row: 53 (section 1/1)
;dec 1 on left (5 -> 6)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b5 f6
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
;twisted stitch
x-add-roller-advance -500
miss + f68 2
x-add-roller-advance -500
knit - f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
miss + f77 2
;end jersey
x-stitch-number 5
knit + f78 2
;dec 1 on right (78 -> 77)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f78 b77
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b77 2
x-add-roller-advance -500
knit + b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
;twisted stitch
x-add-roller-advance -500
miss - b7 2
x-add-roller-advance -500
knit + b7 2
miss - b6 2
;end jersey
x-stitch-number 5
;row: 54 (section 1/1)
;dec 1 on left (6 -> 7)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f6 b7
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
knit + f76 2
miss + f77 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b77 2
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
knit - b7 2
;end jersey
x-stitch-number 5
;row: 55 (section 1/1)
;dec 1 on left (7 -> 8)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b7 f8
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f8 2
x-add-roller-advance -500
knit - f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
;twisted stitch
x-add-roller-advance -500
miss + f76 2
x-add-roller-advance -500
knit - f76 2
;end jersey
x-stitch-number 5
miss + f77 2
;dec 1 on right (77 -> 76)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b77 f76
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
miss - b8 2
;end jersey
x-stitch-number 5
;row: 56 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
knit + f74 2
miss + f75 2
;end jersey
x-stitch-number 5
knit + f76 2
;dec 1 on right (76 -> 75)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f76 b75
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b75 2
x-add-roller-advance -500
knit + b75 2
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
;twisted stitch
x-add-roller-advance -500
miss - b9 2
x-add-roller-advance -500
knit + b9 2
miss - b8 2
;end jersey
x-stitch-number 5
;row: 57 (section 1/1)
;dec 1 on left (8 -> 9)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f8 b9
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
;twisted stitch
x-add-roller-advance -500
miss + f74 2
x-add-roller-advance -500
knit - f74 2
;end jersey
x-stitch-number 5
miss + f75 2
;dec 1 on right (75 -> 74)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b75 f74
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
knit - b9 2
;end jersey
x-stitch-number 5
;row: 58 (section 1/1)
;dec 1 on left (9 -> 10)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b9 f10
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f10 2
x-add-roller-advance -500
knit - f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
miss + f73 2
;end jersey
x-stitch-number 5
knit + f74 2
;dec 1 on right (74 -> 73)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f74 b73
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b73 2
x-add-roller-advance -500
knit + b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
;twisted stitch
x-add-roller-advance -500
miss - b11 2
x-add-roller-advance -500
knit + b11 2
miss - b10 2
;end jersey
x-stitch-number 5
;row: 59 (section 1/1)
;dec 1 on left (10 -> 11)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f10 b11
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
knit + f72 2
miss + f73 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b73 2
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
knit - b11 2
;end jersey
x-stitch-number 5
;row: 60 (section 1/1)
;dec 1 on left (11 -> 12)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b11 f12
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f12 2
x-add-roller-advance -500
knit - f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
;twisted stitch
x-add-roller-advance -500
miss + f72 2
x-add-roller-advance -500
knit - f72 2
;end jersey
x-stitch-number 5
miss + f73 2
;dec 1 on right (73 -> 72)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b73 f72
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
miss - b12 2
;end jersey
x-stitch-number 5
;row: 61 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
knit + f70 2
miss + f71 2
;end jersey
x-stitch-number 5
knit + f72 2
;dec 1 on right (72 -> 71)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f72 b71
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b71 2
x-add-roller-advance -500
knit + b71 2
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
;twisted stitch
x-add-roller-advance -500
miss - b13 2
x-add-roller-advance -500
knit + b13 2
miss - b12 2
;end jersey
x-stitch-number 5
;row: 62 (section 1/1)
;dec 1 on left (12 -> 13)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f12 b13
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
;twisted stitch
x-add-roller-advance -500
miss + f70 2
x-add-roller-advance -500
knit - f70 2
;end jersey
x-stitch-number 5
miss + f71 2
;dec 1 on right (71 -> 70)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b71 f70
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
knit - b13 2
;end jersey
x-stitch-number 5
;row: 63 (section 1/1)
;dec 1 on left (13 -> 14)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b13 f14
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f14 2
x-add-roller-advance -500
knit - f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
miss + f69 2
;end jersey
x-stitch-number 5
knit + f70 2
;dec 1 on right (70 -> 69)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f70 b69
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b69 2
x-add-roller-advance -500
knit + b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
;twisted stitch
x-add-roller-advance -500
miss - b15 2
x-add-roller-advance -500
knit + b15 2
miss - b14 2
;end jersey
x-stitch-number 5
;row: 64 (section 1/1)
;dec 1 on left (14 -> 15)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f14 b15
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
miss + f69 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
knit - b15 2
;end jersey
x-stitch-number 5
;row: 65 (section 1/1)
;dec 1 on left (15 -> 16)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b15 f16
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f16 2
x-add-roller-advance -500
knit - f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
;twisted stitch
x-add-roller-advance -500
miss + f68 2
x-add-roller-advance -500
knit - f68 2
;end jersey
x-stitch-number 5
miss + f69 2
;dec 1 on right (69 -> 68)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b69 f68
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
miss - b16 2
;end jersey
x-stitch-number 5
;row: 66 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
miss + f67 2
;end jersey
x-stitch-number 5
knit + f68 2
;dec 1 on right (68 -> 67)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f68 b67
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b67 2
x-add-roller-advance -500
knit + b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
;twisted stitch
x-add-roller-advance -500
miss - b17 2
x-add-roller-advance -500
knit + b17 2
miss - b16 2
;end jersey
x-stitch-number 5
;row: 67 (section 1/1)
;dec 1 on left (16 -> 17)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f16 b17
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
;twisted stitch
x-add-roller-advance -500
miss + f66 2
x-add-roller-advance -500
knit - f66 2
;end jersey
x-stitch-number 5
miss + f67 2
;dec 1 on right (67 -> 66)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b67 f66
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
;end jersey
x-stitch-number 5
;row: 68 (section 1/1)
;dec 1 on left (17 -> 18)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b17 f18
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f18 2
x-add-roller-advance -500
knit - f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
miss + f65 2
;end jersey
x-stitch-number 5
knit + f66 2
;dec 1 on right (66 -> 65)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f66 b65
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b65 2
x-add-roller-advance -500
knit + b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
;twisted stitch
x-add-roller-advance -500
miss - b19 2
x-add-roller-advance -500
knit + b19 2
miss - b18 2
;end jersey
x-stitch-number 5
;row: 69 (section 1/1)
;dec 1 on left (18 -> 19)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f18 b19
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
miss + f65 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
;end jersey
x-stitch-number 5
;row: 70 (section 1/1)
;dec 1 on left (19 -> 20)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b19 f20
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f20 2
x-add-roller-advance -500
knit - f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
;twisted stitch
x-add-roller-advance -500
miss + f64 2
x-add-roller-advance -500
knit - f64 2
;end jersey
x-stitch-number 5
miss + f65 2
;dec 1 on right (65 -> 64)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b65 f64
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 71 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
miss + f63 2
;end jersey
x-stitch-number 5
knit + f64 2
;dec 1 on right (64 -> 63)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f64 b63
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b63 2
x-add-roller-advance -500
knit + b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 72 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
miss + f63 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 73 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
miss + f63 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 74 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
miss + f63 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 75 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
miss + f63 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 76 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
miss + f63 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 77 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
miss + f63 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 78 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
miss + f63 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 79 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
miss + f63 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 80 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
miss + f63 2
;end jersey
x-stitch-number 5
;inc 1 on right (63 -> 64) by split
x-speed-number 100
rack 1
split + b63 f64 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 81 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
miss - b20 2
;end jersey
x-stitch-number 5
;row: 82 (section 1/1)
;inc 1 on left (20 -> 19) by split
x-speed-number 100
rack 1
split - f20 b19 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
;end jersey
x-stitch-number 5
;row: 83 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
;end jersey
x-stitch-number 5
;row: 84 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
;end jersey
x-stitch-number 5
;row: 85 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
;end jersey
x-stitch-number 5
;row: 86 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
;end jersey
x-stitch-number 5
;inc 1 on right (64 -> 65) by split
x-speed-number 100
rack -1
split + f64 b65 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
;end jersey
x-stitch-number 5
;row: 87 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
miss + f65 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
;end jersey
x-stitch-number 5
;row: 88 (section 1/1)
;inc 1 on left (19 -> 18) by split
x-speed-number 100
rack -1
split - b19 f18 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
miss + f65 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
miss - b18 2
;end jersey
x-stitch-number 5
;row: 89 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
miss + f65 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
miss - b18 2
;end jersey
x-stitch-number 5
;row: 90 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
miss + f65 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
miss - b18 2
;end jersey
x-stitch-number 5
;row: 91 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
miss + f65 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
miss - b18 2
;end jersey
x-stitch-number 5
;row: 92 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
miss + f65 2
;end jersey
x-stitch-number 5
;inc 1 on right (65 -> 66) by split
x-speed-number 100
rack 1
split + b65 f66 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
miss - b18 2
;end jersey
x-stitch-number 5
;row: 93 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
miss - b18 2
;end jersey
x-stitch-number 5
;row: 94 (section 1/1)
;inc 1 on left (18 -> 17) by split
x-speed-number 100
rack 1
split - f18 b17 2
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
;end jersey
x-stitch-number 5
;row: 95 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
;end jersey
x-stitch-number 5
;row: 96 (section 1/1)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit + f40 2
knit + f42 2
knit + f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
knit - b43 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b41 2
knit - b39 2
knit - b37 2
knit - b35 2
knit - b33 2
knit - b31 2
knit - b29 2
knit - b27 2
knit - b25 2
knit - b23 2
knit - b21 2
knit - b19 2
knit - b17 2
;end jersey
x-stitch-number 5
knit + b17 2
knit + b19 2
knit + b21 2
knit + b23 2
knit + b25 2
knit + b27 2
knit + b29 2
knit + b31 2
knit + b33 2
knit + b35 2
knit + b37 2
knit + b39 2
miss + b40 2
;row: 97 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
knit + f28 3
knit + f30 3
knit + f32 3
knit + f34 3
knit + f36 3
knit + f38 3
miss + f39 3
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b39 3
knit - b37 3
knit - b35 3
knit - b33 3
knit - b31 3
knit - b29 3
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
;end jersey
x-stitch-number 5
;row: 98 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
knit + f28 3
knit + f30 3
knit + f32 3
knit + f34 3
knit + f36 3
;twisted stitch
x-add-roller-advance -500
miss + f38 3
x-add-roller-advance -500
knit - f38 3
;end jersey
x-stitch-number 5
miss + f39 3
;dec 1 on right (39 -> 38)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b39 f38
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b37 3
knit - b35 3
knit - b33 3
knit - b31 3
knit - b29 3
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
;end jersey
x-stitch-number 5
;row: 99 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
knit + f28 3
knit + f30 3
knit + f32 3
knit + f34 3
knit + f36 3
miss + f37 3
;end jersey
x-stitch-number 5
knit + f38 3
;dec 1 on right (38 -> 37)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f38 b37
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b37 3
x-add-roller-advance -500
knit + b37 3
knit - b35 3
knit - b33 3
knit - b31 3
knit - b29 3
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
;end jersey
x-stitch-number 5
;row: 100 (section 1/2)
;inc 1 on left (17 -> 16) by split
x-speed-number 100
rack -1
split - b17 f16 3
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
knit + f28 3
knit + f30 3
knit + f32 3
knit + f34 3
;twisted stitch
x-add-roller-advance -500
miss + f36 3
x-add-roller-advance -500
knit - f36 3
;end jersey
x-stitch-number 5
miss + f37 3
;dec 1 on right (37 -> 36)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b37 f36
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b35 3
knit - b33 3
knit - b31 3
knit - b29 3
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
miss - b16 3
;end jersey
x-stitch-number 5
;row: 97 (section 2/2)
;dec 4 on left (40 -> 44)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -2
xfer f40 b42
xfer f42 b44
rack 2
xfer b41 f43
xfer b42 f44
xfer b43 f45
xfer b44 f46
rack -2
xfer f43 b45
xfer f45 b47
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f44 2
x-add-roller-advance -500
knit - f44 2
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
;twisted stitch
x-add-roller-advance -500
miss - b45 2
x-add-roller-advance -500
knit + b45 2
miss - b44 2
;end jersey
x-stitch-number 5
;row: 98 (section 2/2)
;dec 1 on left (44 -> 45)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f44 b45
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f46 2
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
;end jersey
x-stitch-number 5
;inc 1 on right (66 -> 67) by split
x-speed-number 100
rack -1
split + f66 b67 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
knit - b45 2
;end jersey
x-stitch-number 5
;row: 99 (section 2/2)
;dec 2 on left (45 -> 47)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f46 b47
xfer f48 b49
rack 1
xfer b47 f48
xfer b45 f46
rack -1
xfer f46 b47
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
miss + f67 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
knit - b47 2
;end jersey
x-stitch-number 5
;row: 100 (section 2/2)
;dec 1 on left (47 -> 48)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b47 f48
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f48 2
x-add-roller-advance -500
knit - f48 2
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
miss + f67 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
;twisted stitch
x-add-roller-advance -500
miss - b49 2
x-add-roller-advance -500
knit + b49 2
miss - b48 2
;end jersey
x-stitch-number 5
;row: 101 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
knit + f28 3
knit + f30 3
knit + f32 3
knit + f34 3
miss + f35 3
;end jersey
x-stitch-number 5
knit + f36 3
;dec 1 on right (36 -> 35)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f36 b35
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b35 3
x-add-roller-advance -500
knit + b35 3
knit - b33 3
knit - b31 3
knit - b29 3
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
miss - b16 3
;end jersey
x-stitch-number 5
;row: 102 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
knit + f28 3
knit + f30 3
knit + f32 3
;twisted stitch
x-add-roller-advance -500
miss + f34 3
x-add-roller-advance -500
knit - f34 3
;end jersey
x-stitch-number 5
miss + f35 3
;dec 1 on right (35 -> 34)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b35 f34
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b33 3
knit - b31 3
knit - b29 3
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
miss - b16 3
;end jersey
x-stitch-number 5
;row: 103 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
knit + f28 3
knit + f30 3
knit + f32 3
miss + f33 3
;end jersey
x-stitch-number 5
knit + f34 3
;dec 1 on right (34 -> 33)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f34 b33
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b33 3
x-add-roller-advance -500
knit + b33 3
knit - b31 3
knit - b29 3
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
miss - b16 3
;end jersey
x-stitch-number 5
;row: 104 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
knit + f28 3
knit + f30 3
;twisted stitch
x-add-roller-advance -500
miss + f32 3
x-add-roller-advance -500
knit - f32 3
;end jersey
x-stitch-number 5
miss + f33 3
;dec 1 on right (33 -> 32)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b33 f32
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b31 3
knit - b29 3
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
miss - b16 3
;end jersey
x-stitch-number 5
;row: 101 (section 2/2)
;dec 1 on left (48 -> 49)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f48 b49
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
miss + f67 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
knit - b49 2
;end jersey
x-stitch-number 5
;row: 102 (section 2/2)
;dec 1 on left (49 -> 50)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b49 f50
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f50 2
x-add-roller-advance -500
knit - f50 2
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
miss + f67 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
;twisted stitch
x-add-roller-advance -500
miss - b51 2
x-add-roller-advance -500
knit + b51 2
miss - b50 2
;end jersey
x-stitch-number 5
;row: 103 (section 2/2)
;dec 1 on left (50 -> 51)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f50 b51
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
miss + f67 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
knit - b51 2
;end jersey
x-stitch-number 5
;row: 104 (section 2/2)
;dec 1 on left (51 -> 52)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b51 f52
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f52 2
x-add-roller-advance -500
knit - f52 2
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
miss + f67 2
;end jersey
x-stitch-number 5
;inc 1 on right (67 -> 68) by split
x-speed-number 100
rack 1
split + b67 f68 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
;twisted stitch
x-add-roller-advance -500
miss - b53 2
x-add-roller-advance -500
knit + b53 2
miss - b52 2
;end jersey
x-stitch-number 5
;row: 105 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
knit + f28 3
knit + f30 3
;end jersey
x-stitch-number 5
knit + f32 3
;dec 2 on right (32 -> 30)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b31 f30
xfer b29 f28
rack 1
xfer f30 b29
xfer f32 b31
rack -1
xfer b31 f30
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b29 3
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
miss - b16 3
;end jersey
x-stitch-number 5
;row: 106 (section 1/2)
;inc 1 on left (16 -> 15) by split
x-speed-number 100
rack 1
split - f16 b15 3
rack 0
x-speed-number 300
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
knit + f28 3
miss + f29 3
;end jersey
x-stitch-number 5
knit + f30 3
;dec 1 on right (30 -> 29)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f30 b29
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b29 3
x-add-roller-advance -500
knit + b29 3
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
knit - b15 3
;end jersey
x-stitch-number 5
;row: 107 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
;twisted stitch
x-add-roller-advance -500
miss + f28 3
x-add-roller-advance -500
knit - f28 3
;end jersey
x-stitch-number 5
miss + f29 3
;dec 1 on right (29 -> 28)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b29 f28
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
knit - b15 3
;end jersey
x-stitch-number 5
;row: 108 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
knit + f26 3
miss + f27 3
;end jersey
x-stitch-number 5
knit + f28 3
;dec 1 on right (28 -> 27)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f28 b27
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b27 3
x-add-roller-advance -500
knit + b27 3
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
knit - b15 3
;end jersey
x-stitch-number 5
;row: 105 (section 2/2)
;dec 1 on left (52 -> 53)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f52 b53
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
knit - b53 2
;end jersey
x-stitch-number 5
;row: 106 (section 2/2)
;dec 1 on left (53 -> 54)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b53 f54
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f54 2
x-add-roller-advance -500
knit - f54 2
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
;twisted stitch
x-add-roller-advance -500
miss - b55 2
x-add-roller-advance -500
knit + b55 2
miss - b54 2
;end jersey
x-stitch-number 5
;row: 107 (section 2/2)
;dec 1 on left (54 -> 55)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f54 b55
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
knit - b55 2
;end jersey
x-stitch-number 5
;row: 108 (section 2/2)
;dec 1 on left (55 -> 56)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b55 f56
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f56 2
x-add-roller-advance -500
knit - f56 2
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
;twisted stitch
x-add-roller-advance -500
miss - b57 2
x-add-roller-advance -500
knit + b57 2
miss - b56 2
;end jersey
x-stitch-number 5
;row: 109 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
;twisted stitch
x-add-roller-advance -500
miss + f26 3
x-add-roller-advance -500
knit - f26 3
;end jersey
x-stitch-number 5
miss + f27 3
;dec 1 on right (27 -> 26)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b27 f26
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
knit - b15 3
;end jersey
x-stitch-number 5
;row: 110 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
knit + f24 3
miss + f25 3
;end jersey
x-stitch-number 5
knit + f26 3
;dec 1 on right (26 -> 25)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f26 b25
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b25 3
x-add-roller-advance -500
knit + b25 3
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
knit - b15 3
;end jersey
x-stitch-number 5
;row: 111 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
;twisted stitch
x-add-roller-advance -500
miss + f24 3
x-add-roller-advance -500
knit - f24 3
;end jersey
x-stitch-number 5
miss + f25 3
;dec 1 on right (25 -> 24)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b25 f24
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b23 3
knit - b21 3
knit - b19 3
knit - b17 3
knit - b15 3
;end jersey
x-stitch-number 5
;row: 112 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
knit + f22 3
miss + f23 3
;end jersey
x-stitch-number 5
knit + f24 3
;dec 1 on right (24 -> 23)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f24 b23
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b23 3
x-add-roller-advance -500
knit + b23 3
knit - b21 3
knit - b19 3
knit - b17 3
knit - b15 3
;end jersey
x-stitch-number 5
;row: 109 (section 2/2)
;dec 1 on left (56 -> 57)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f56 b57
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
knit - b57 2
;end jersey
x-stitch-number 5
;row: 110 (section 2/2)
;dec 1 on left (57 -> 58)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b57 f58
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f58 2
x-add-roller-advance -500
knit - f58 2
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
;end jersey
x-stitch-number 5
;inc 1 on right (68 -> 69) by split
x-speed-number 100
rack -1
split + f68 b69 2
rack 0
x-speed-number 300
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
;twisted stitch
x-add-roller-advance -500
miss - b59 2
x-add-roller-advance -500
knit + b59 2
miss - b58 2
;end jersey
x-stitch-number 5
;row: 111 (section 2/2)
;dec 1 on left (58 -> 59)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f58 b59
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
miss + f69 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
knit - b59 2
;end jersey
x-stitch-number 5
;row: 112 (section 2/2)
;dec 1 on left (59 -> 60)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b59 f60
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f60 2
x-add-roller-advance -500
knit - f60 2
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
miss + f69 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
;twisted stitch
x-add-roller-advance -500
miss - b61 2
x-add-roller-advance -500
knit + b61 2
miss - b60 2
;end jersey
x-stitch-number 5
;row: 113 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
;twisted stitch
x-add-roller-advance -500
miss + f22 3
x-add-roller-advance -500
knit - f22 3
;end jersey
x-stitch-number 5
miss + f23 3
;dec 1 on right (23 -> 22)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b23 f22
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b21 3
knit - b19 3
knit - b17 3
knit - b15 3
;end jersey
x-stitch-number 5
;row: 114 (section 1/2)
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f16 3
knit + f18 3
knit + f20 3
miss + f21 3
;end jersey
x-stitch-number 5
knit + f22 3
;dec 1 on right (22 -> 21)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer f22 b21
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss - b21 3
x-add-roller-advance -500
knit + b21 3
knit - b19 3
knit - b17 3
knit - b15 3
;end jersey
x-stitch-number 5
miss - f0 3
;tuck to move carrier 5 from 45 to 15
x-roller-advance 0
x-roller-advance 500
;drop finish
out 3
;stitch pattern tube: rib for 16 rows
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b19 f19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b21 5
knit - f19 5
knit - b17 5
knit - b15 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f19 b19
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f18 b18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f16 5
knit + b18 5
knit + f20 5
miss + f21 5
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b18 f18
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
drop f16
drop f18
drop f20
drop b15
drop b17
drop b19
drop b21
x-roller-advance 0
miss - f0 5
x-roller-advance 500
;row: 113 (section 2/2)
;dec 1 on left (60 -> 61)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer f60 b61
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
knit + f62 2
knit + f64 2
knit + f66 2
knit + f68 2
miss + f69 2
;end jersey
x-stitch-number 5
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b69 2
knit - b67 2
knit - b65 2
knit - b63 2
knit - b61 2
;end jersey
x-stitch-number 5
;row: 114 (section 2/2)
;dec 1 on left (61 -> 62)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack 1
xfer b61 f62
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed f (1 pass count)
x-stitch-number 5
;begin jersey
;twisted stitch
x-add-roller-advance -500
miss + f62 2
x-add-roller-advance -500
knit - f62 2
knit + f64 2
knit + f66 2
;twisted stitch
x-add-roller-advance -500
miss + f68 2
x-add-roller-advance -500
knit - f68 2
;end jersey
x-stitch-number 5
miss + f69 2
;dec 1 on right (69 -> 68)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
rack -1
xfer b69 f68
rack 0
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;insert stitch pattern for bed b (1 pass count)
x-stitch-number 5
;begin jersey
knit - b67 2
knit - b65 2
knit - b63 2
miss - b62 2
;end jersey
x-stitch-number 5
;tuck to move carrier 6 from 45 to 62
x-roller-advance 0
tuck + b46 6
tuck + f47 6
tuck + b50 6
tuck + f51 6
tuck + b54 6
tuck + f55 6
tuck + b58 6
tuck + f59 6
x-roller-advance 500
;drop finish
out 5
out 2
;stitch pattern tube: rib for 16 rows
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed f
;begin rib (bf)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f64 b64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit + f62 6
knit + b64 6
knit + f66 6
knit + f68 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b64 f64
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
;insert stitch pattern for bed b
;begin rib (fb)
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer b65 f65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
knit - b67 6
knit - f65 6
knit - b63 6
miss - b62 6
x-speed-number 300
x-stitch-number 2
x-roller-advance 0
xfer f65 b65
x-speed-number 300
x-stitch-number 5
x-roller-advance 500
;end rib
drop f62
drop f64
drop f66
drop f68
x-add-roller-advance 2000
drop b63
drop b65
drop b67
out 6
x-roller-advance 0
drop b46
drop f47
drop b50
drop f51
drop b54
drop f55
drop b58
drop f59
x-roller-advance 500
